version: 2.1 

jobs: 
  save_hello_world_output: 
    docker:
      - image: cimg/base:stable
    steps: 
      - checkout 
      - run:
          name: "Save Hello World Context Output"
          command: echo "text to output here" > output.txt 
      - persist_to_workspace: 
          root: .circleci 
          paths: 
            - output 

  print_output_file: 
    docker:
      - image: cimg/base:stable
    steps: 
      - checkout 
      - attach_workspace:
          at: /age-game/.circleci  
      
      - run: 
          name: "Print Output File" 
          command: echo cat output.txt  
       

workflows:
  print-store-output-context:
   jobs:
      - save_hello_world_output
      - print_output_file:
          requires: 
            - save_hello_world_output           
